version: '3'

services:
  app:
    build: .
    command: bash -c "make build"
    depends_on:
      - db
    environment:
      DSN: "host=db user=postgres dbname=postgres password=password sslmode=disable"

  db:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/schema:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
